### ISSUE TITLE
Unresolved dependency 'Benchmark'

### ISSUE THREAD

**Issue by brian-carroll** [fredcy/elm-core-benchmark#2]
Hey, saw the discussion about this on elm-dev email list, thought it was really interesting and liked the graphs you made. I wanted to play with this repo and try doing something similar with some of the other functions in the List package, just for a learning project.

But I seem to be missing a dependency on a "Benchmark" module. It's not listed in `elm-package.json`. Maybe it lives somewhere that's `gitignore`d? Can you let me know where to find the module?

Here's the output from running `make` on a freshly cloned version of this repo.

```
 > make elm.js
elm make Main.elm --output=elm.js --yes
Starting downloads...

  ● elm-lang/html 1.1.0
  ● elm-community/elm-test 1.1.0
  ● elm-lang/virtual-dom 1.1.1

Packages configured successfully!
  ● elm-lang/core 4.0.5
I cannot find module 'Benchmark'.

Module 'Main' is trying to import it.

Potential problems could be:
  * Misspelled the module name
  * Need to add a source directory or new dependency to elm-package.json
make: *** [elm.js] Error 1

```

**Comment by fredcy** [comment]
I just updated the README.md to give some installation directions.

**Comment by brian-carroll** [comment]
Thank you so much for the quick response, much appreciated! :+1:
